#!/bin/bash
# Programa que ejecuta el ejecutable que está en la carpeta /bin

echo "Programa que ejecuta el ejecutable que está en la carpeta \bin"

cd ~/Escritorio/ising/bin

echo "Ejecución en proceso"

./ejecutable.e

echo "Moviendo resultados a la carpeta \test"

mv energia.txt ~/Escritorio/ising/test
mv magnetizacion.txt ~/Escritorio/ising/test
mv energia_std.txt ~/Escritorio/ising/test
mv magnet_std.txt ~/Escritorio/ising/test
mv magnet_corr.txt ~/Escritorio/ising/test
mv cv.txt ~/Escritorio/ising/test

echo "Archivos movidos con éxito"

cd ~/Escritorio/ising/src

echo "Gracias por volar con FlyJosu"
